# Numpy

In [ ]:
#Numpy is a library for supporting large,multi-dimensional array and matrices and large number of function to operate on it
#numpy's most useful feature is n dimensional array object(aka n-d array)
#but why do we need it? tell you after the below example

In [2]:
#this is how you create an array
import numpy as np
a=np.array([1,2,3])
print(a)
print(a[0])
print(a[1])
print(a[2])

[1 2 3]


In [3]:
#you will it is similar to list but
#numpy arrays have advantages over list
#1.) they use less space
#2.) they are fast
#3.) It is more convinient

#we will see them with the proof

In [8]:
import sys
import numpy as np

# list
l=range(1000)
print(sys.getsizeof(5)*len(l)) #it prints the whole memory of list, 
                                #"sys.getsizeof(5)" gives the of the number you can put num other than 5
    
#numpy array
arr=np.arange(1000) #it array of 0 to 999 ,read it like this "a range"
print(arr.size*arr.itemsize)

#you will see the difference 
#so it is clear that list use more space than numpy arrays

28000
4000


In [14]:
import time
import numpy as np
size=1000000 #1 million

#list
l1=range(size)
l2=range(size)
start=time.time()
l3=[(x+y) for x,y in zip(l1,l2)] #it will add the list element corresponding to each other like l3[0]=l1[0]+l2[0]
print("pythin list took time ",(time.time()-start)*1000)

#numpy array
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
a3=a2+a1 #adding both array more convinient than list
print("numpy array took time",(time.time()-start)*1000)

#you can see the difference
#numpy array are 100 times faster than list

pythin list took time  235.1059913635254
numpy array took time 3.0612945556640625


# Accessing Rows and columns

In [5]:
import numpy as np
a=np.array([[12,13,14,15],[45,32,56,67]])

print(a[1,1])
print(a[0,:])
print(a[1,:])

32
[12 13 14 15]
[45 32 56 67]


In [6]:
print(a[2,:])

IndexError: index 2 is out of bounds for axis 0 with size 2

# Now functionalities and operations

In [18]:
# using ndim() which gives out which dimension is of array
a=np.array([1,2,3,4,5,6])#1 d arrays
print(a.ndim)

b=np.array([[1,2],[3,4],[5,6]])
print(b.ndim)

1
2


In [19]:
#using itemsize gives out byte of each elment in array
a=np.array([1,2,3,4,5,6,7])
print(a.itemsize)

4


In [21]:
#using dtype gives out data type of each element in array
a=np.array([1,5,67,89,0,99])
print(a.dtype)

int32


In [26]:
#we can also change the data type
a=np.array([[1,23],[4,5],[678,234]],dtype=np.float64)
print(a)
print(a.dtype)

[[  1.  23.]
 [  4.   5.]
 [678. 234.]]
float64


In [30]:
# using shape
a=np.array([[12,34],[1,2],[6,7],[90,44]])
# a is of array(matrix) 4 x 2 ,(4->row,2->column)
#shape is use to give that dimension (4 X 2)
print(a.shape)

(4, 2)


In [41]:
#to make a matrix of zeroes
import numpy as np
a=np.zeros( (2,2) )
print(a)

[[0. 0.]
 [0. 0.]]


In [40]:
#to make a matrix of ones
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
# as in list we are using range(1,1000) 
a=np.arange(6)
print(a)

a=np.arange(1,6)
print(a)

a=np.arange(1,6,2)
print(a)

[0 1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [81]:
#using min()->return minimum element and max()->return maximum element
a=np.array([[23,1],[45,6],[99,2]])
print(a)
print()
print(a.min())
print(a.max())

[[23  1]
 [45  6]
 [99  2]]

1
99


# linspace

In [ ]:
#linspace gives out array of equally spaced numbers like below

In [51]:
a=np.linspace(1,5,10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[ 1.   5.5 10. ]


In [53]:

a=np.linspace(0,10,3)
print(a)

[ 0.  5. 10.]


# Reshape

In [66]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print()
print(a.shape)
print()
#we use reshape as follow

print(a.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]

(3, 2)

[[1 2 3]
 [4 5 6]]


In [70]:
a=np.array([[1,2],[3,4],[5,6]])
#shape is (3,2)
print(a.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Ravel

In [ ]:
#ravel function will make any array dimenson into 1-d array

In [74]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print()
print(a.ravel())

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[1 2 3 4 5 6 7 8]


# Arithmatic

In [60]:
a=np.array([1,2,3,4,5,6])
b=np.array([8,9,10,11,12,13])
c=a+b
print(c)
c=a-b
print(c)

[ 9 11 13 15 17 19]
[-7 -7 -7 -7 -7 -7]


In [57]:
a=np.array([1,2,3,4,5,6])
b=np.array([8,9,10,11,12,13])
c=a*b
print(c)

[ 8 18 30 44 60 78]


In [58]:
a=np.array([1,2,3,4,5,6])
b=np.array([8,9,10,11,12,13])
c=a/b
print(c)

[0.125      0.22222222 0.3        0.36363636 0.41666667 0.46153846]


# Sum function

In [85]:
a=np.array([[1,2],[2,3],[3,4]])
print(a.sum())
print(a.sum(axis=0))#axis=0 means y axis or you can say sum of each column
print(a.sum(axis=1))#axis=1 means x axis or you can say sum of each row

15
[6 9]
[3 5 7]


# sqrt function

In [ ]:
#used for return square root of each element in array

In [87]:
a=np.array([4,16,9,25,7])
print(np.sqrt(a))

[2.         4.         3.         5.         2.64575131]
