# Basics of Python

In [ ]:
print("Hello World")

Using and reassigning variables

In [ ]:
a="Aryan"
print(a)

In [ ]:
a="Hello World"
print(a)

In [3]:
#using type(), it prints out the data type of the variable 
a="Aryan"
type(a)

str

In [3]:
#how to find address of a variable
# id() is the function used to give the address of the given variable
var=12
print(id(12))

140723511175296


In [4]:
b=10
type(b)

int

In [ ]:
#addition
4+3

In [ ]:
#multiplication
4*2

In [2]:
#using powers and exponents 
a=4**3 #it is considered as 4 power 3(4^)
print(a)

64


# Strings


In [1]:
#how to print in a same line
print("Aryan",end=" ")
print("Patel")

print("Aryan")
print("Patel")

Aryan Patel
Aryan
Patel


In [ ]:
#string indexing
d="Aryan"
print(d[ :2])

In [ ]:
c="Aryan"
c[2:]

In [ ]:
e="Aryan"
c[:3]

In [ ]:
p="Aryan"
p[1:2]

In [ ]:
s1="Aryan"
s2="Patel"
print(s1+s2)

In [1]:
#important to note 
a=1
print("Aryan"+ a)
#you will get an error

TypeError: can only concatenate str (not "int") to str

In [12]:
#you can do like these
a=1
print("Aryan"+str(a))#str() is used to convert to strings

Aryan1


In [ ]:
a1="Aryan"
a2="Patel"
print(a1+"Hemant"+a2)
#you can add spaces like a1+" "+"Hemant"+" "+a2 or
#a1+" Hemant "+a2

In [ ]:
b1="aryan"
print(b1.title())
#using title() first letter will become capital and rest all will be small

In [ ]:
d1="same"
print(d1.upper())
#using upper() written string letters will be all in capital case

In [ ]:
d2="DEJAVU"
print(d2.lower())
#using lower() written string letters will be all in small case

In [ ]:
d3="aRyan"
print(d3.title())
print(d3.upper())
print(d3.lower())

In [ ]:
d4=" Aryan is crazy "
print(d4)
print(d4+"shsdfhusfh")
print(d4.strip())            #will remove spaces all left and right
print("Intro"+d4.strip()+"about coding")
print(d4.lstrip())                    #will remve spaces from left
print("Intro"+d4.lstrip()+"about coding")
print(d4.rstrip())
print("Intro"+d4.rstrip()+"about coding")

In [5]:
a=input("Enter String: ")
print(a)
#len() is used for finding the length of string
b=len(a)
print(b)


Enter String: aryan
aryan
5


In [12]:
# \n for new line
print("Aryan \n Juhil \n Parth")

Aryan 
 Juhil 
 Parth


# String Formatting

In [ ]:
# %s --> strings
# %d --> integer
# %f --> floating point numbers 
# %b --> binary format

In [9]:
#Formatting with % Operator
print("Aryan Patel is %s" %'NIT')
print("My age is %d" %23)

x = 'looked'
print("Misha %s and %s around" %('walked',x))

x="jogged"
c="Aryan %s and %s around" %('walked',x)
print(c)

print("PI value is %f" %3.14)
print("PI value is %5.1f" %3.14) 
print("PI value is %3.2f" %3.14)

Aryan Patel is NIT
My age
 is 23
Misha walked and looked around
Aryan walked and jogged around
PI value is 3.140000
PI value is   3.1
PI value is 3.14


In [ ]:
# by using .format()

In [15]:
print("Aryan {}".format('Patel'))
#using keywords
print("{2} {1} {0}".format('Aryan','Patel','NIT'))# 0 -> Aryan, 1 -> Patel, 2 ->NIT

print("We are {a},{b} and {c}".format(a='Humans',b='homosapeans',c='mammals'))
#to avoid repetation
print('The first {p} was alright, but the {p} {p} was tough.'.format(p = 'second'))

Aryan Patel
NIT Patel Aryan
We are Humans,homosapeans and mammals


In [1]:
#you can do same with numbers
print("Nine = {}".format(9))
print("a={x} b={y} c={z}".format(x=1,y=2,z=3))
#for floating
print("PI:{}".format(3.14159))
print("PI:{}".format(3.14159))

Nine = 9
a=1 b=2 c=3
PI:3.14159
PI:3.14159


In [ ]:
#for floating point numbers

# Lists


In [ ]:
list=['Aryan','hello','emoji']
print(list)
print(list[0])
print(list[1])
print(list[2])
print(list[-1])
print(list[-2])
print(list[-3])


In [ ]:
bikes=['ninja','ducati','bmw']
print(bikes)
print(bikes[0].title())
print(bikes[0].upper())

print("My bike is "+bikes[1])

In [ ]:
#Removing an Item Using the del Statement
#using del we can delete the element we cannot store that deleted element like we do using 'pop' statement 
comp=['hp','dell','lenovo','mac']
del comp[0],comp[1]
print(comp)


In [ ]:
#using pop statement 
#if we doesn't assign element in pop it will autematicaly delete last element as shown
maths=['algebra','calculas','geometry','probablity']
maths.pop()
print(maths)

In [ ]:
#in pop statement element will delete also it can be stored like shown below
p=['gandhi','ramesh','sardar','nehru']
a=p.pop(0)
print(p)

print(a)

In [ ]:
#sometimes we donot the position as list can contain too many elements we can us name of in remove statement
#also refer notes important note is these
p=['gandhi','ramesh','sardar','nehru']
p.remove('ramesh')
print(p)

In [ ]:
#append
#append will add element at last only you cannot specify position
a=['aryan','federal','history']
a.append('guwahati')
print(a)


In [ ]:
#insert()
#in insert you can add element at a specified position
a=['aryan','federal','history']
a.insert(0,'gandhi')
print(a)
a.insert(2,'bappa')
print(a)

In [ ]:
#using sort and sorted
#in sorted 
a=['zigmondy','asap','lol','bae']
print(sorted(a))
print(a)

In [ ]:
a=['zigmondy','asap','lol','bae']
a.sort()
print(a)
print(a)


In [ ]:
#reverse=False means ascending order
#reverse=True means descending order
a=['zigmondy','asap','lol','bae']
a.sort(reverse=False)
print(a)
a.sort(reverse=True)
print(a)

In [ ]:
#using reverse() we can print whole list in reverse order
r=['gypsy','true','false','kind']
r.reverse()
print(r)

In [ ]:
#Python’s range() function makes it easy to generate a series of numbers.
#For example, you can use the range() function to print a series of numbers like this:
for num in range(1,5):
    print(num)

In [ ]:
for num in range(1,7):
    print(num)

In [ ]:
#Using range() to Make a List of Numbers
#If you want to make a list of numbers, you can convert the results of range() 
#directly into a list using the list() function. When you wrap list() around a call to the range() function,
#the output will be a list of numbers
a=list(range(0,5))
print(a)

# Tuples

In [ ]:
a=list(range(0,10,2))
print(a)
#(0,10,2) here 0 will be intial and 10 will be last & 2 will be addition number 
#i.e. intial number :0 , next number to be print:0+2=2 

In [3]:
#what is difference between tuples and lists 
#tuples are immutable(means it can not be change)
#while list are mutable(we can change)
#let see in down cell

In [4]:
a=('Aryan','Bike')
a[0]='Patel'
#you cannot change elements in tuple
#run it u will understand
#Error u will get: 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

In [ ]:
#tuples have same methods as list have only difference is of changing element
a=('fort','gangam','kp')
for b in range(0,3):
    print(a[b])
    print(b)

# Dictionary

In [ ]:
#in dictionary{'a':'b'},'a' is known as keys and 'b' is known as values
a={1:'Aryan',3:'Patel',2:'Hemant'}
print(a[1]+" "+a[2]+" "+a[3])

TypeError: can only concatenate str (not "int") to str

In [ ]:
#not related to dictionary
a=1
print(a+1)

In [6]:
#you can add elements from outside of dictionary
a={'ar':'aryan','ty':'thank you'}
print(a)
a['LoL']='Laugh out loud'
a['asap']='as soon as possible'

print(a)

{'ar': 'aryan', 'ty': 'thank you'}
{'ar': 'aryan', 'ty': 'thank you', 'LoL': 'Laugh out loud', 'asap': 'as soon as possible'}


In [ ]:
#you can also add element to emplty dictionary
b={}
print(b)
b['a']='aryan'
b['city']='surat'
print(b)

In [ ]:
#changing values
a={'ar':'aryan','ty':'thank you'}
print(a['ar'])

a['ar']='Guwahati'
print(a['ar'])

In [ ]:
#removing elements
a={'ar':'aryan','ty':'thank you'}
print(a)

del a['ar']

print(a)

In [ ]:
#there can be same information for different object as given below
a={'ar':'aryan','ty':'aryan'}
print(a['ar'])
print(a['ty'])

In [9]:
#use of items() very important
a={'1':'one','2':'two','3':'three'}
for l,n in a.items():
    print('Number' +l+' is '+n)


Number1 is one
Number2 is two
Number3 is three


In [ ]:
fav_lang={'aryan':'hindi','ketan':'english','agrim':'gujarati'}

friends=['ketan','agrim']
for name in fav_lang:
    if name in friends:
        print("My friend "+name+" favourit language is "+fav_lang[name].title())

In [ ]:
#you can also insert list in a dictionary
food={'gujarati':['dhokla','samosa'],'punjabi':['lassi','paneer'],'south indian':['dhosa','sambhar']}
for people,style in food.items():
    for fooditems in style:
        print(people+"food is "+food[people])

# If Statement

In [ ]:
a=['Aryan','patel','hi','buggati']
c='patel'

if c not in a:
    print("yes")
else:
    print("no")

In [ ]:
a=16
if a>=16:
    print("yes")

In [ ]:
#elif means 'else if' as we are using c
a='good'
if a=='bad':
    print("bad")
elif a=='good':
    print("Good")
else:
    print("no output")


In [ ]:
a='ghsadhgd'
if a=='bad':
    print("bad")
elif a=='good':
    print("Good")
else:
    print("no match")


In [ ]:
age=12
price=list(range(0,5))
if age<4:
    price=0
elif age<18:
    price[0]=5

else:
    price=15    
print("Price is "+str(price)+".")

# Functions


In [ ]:
#defining a function
#calling a fuction
def fnc():
    print("Aryan Patel created fuction")
 
fnc()
   

In [ ]:
def display_message():
    print("I am exciting about learning python functions")
    
display_message()

In [ ]:
def describe_pet(pet_name,pet_type='dog'):
    print("I have a "+pet_type)
    print("His Name is "+pet_name)

describe_pet('sheru')
print("\n")
describe_pet('fissy','fish')

In [5]:
def build_person(first_name,last_name,age):
    person={'first':first_name,'last':last_name}
    if age:
        person['age']=age
    return person

musician=build_person('jimi','hendrix',23)
print(musician)

{'first': 'jimi', 'last': 'hendrix', 'age': 23}


In [15]:
# * this is use for list

def pizza(size, *toppings):
    print('In a pizza making of size',size,'inch with following toppings:')
    for top in toppings:
        print('-',toppings)
        
pizza('13','cheese','paneer','veges')
print('\n')
pizza('4','pepper')

def pizza(size, *toppings):
    print('In a pizza making of size',size,'inch with following toppings:')
    for top in toppings:
        print('-',top)
        
pizza('13','cheese','paneer','veges')
print('\n')
pizza('4','pepper')

In a pizza making of size 13 inch with following toppings:
- ('cheese', 'paneer', 'veges')
- ('cheese', 'paneer', 'veges')
- ('cheese', 'paneer', 'veges')


In a pizza making of size 4 inch with following toppings:
- ('pepper',)
In a pizza making of size 13 inch with following toppings:
- cheese
- paneer
- veges


In a pizza making of size 4 inch with following toppings:
- pepper


In [17]:
#** we use dictionary
def intro(first_name,last_name,**user_info):
    profile={}
    profile['first name']=first_name
    profile['last name']=last_name
    for key,value in user_info.items():
        profile[key]=value
    return profile

a=intro('Aryan','Patel',location='surat',age='18')
print(a)

{'first name': 'Aryan', 'last name': 'Patel', 'location': 'surat', 'age': '18'}


# Classes and Object

In [ ]:
#constructors: def __init__(self)
#self is the first argument to be passed in Constructor and Instance Method
#self used to access the attributes of the class

In [3]:
class students:
    
    def __init__(self, name, rollno,age, m1, m2, m3):
        self.nu=rollno
        self.n=name
        self.a=age
        self.mrk1=m1
        self.mrk2=m2
        self.mrk3=m3
        
    def details(self):
        print("Student Name is ",self.n)
        print("\tRoll no.: ",self.nu)
        print("\tAge: ",self.a)
        print("\tMarks in Science: "+self.mrk1+" ; Maths: "+self.mrk2+" ; English: ",self.mrk3)

n=int(input("How many students = "))
s={}
na={}
roll={}
ag={}
mk1={}
mk2={}
mk3={}
for i in range(1,n+1):
    na[i]=input("Name: ")
    roll[i]=input("Roll No.: ")
    ag[i]=input("Age: ")
    mk1[i]=input("Marks(sci): ")
    mk2[i]=input("Marks(Maths): ")
    mk3[i]=input("Marks(Eng): ")
    
print('\n')
    
print('--------Details of students--------')
    
for i in range(1,n+1):
    s[i]=students(na[i],roll[i],ag[i],mk1[i],mk2[i],mk3[i])
    students.details(s[i])
    print('\n')

print('-----------------------------------')
        


How many students = 3
Name: Aryan
Roll No.: 56
Age: 45
Marks(sci): 56
Marks(Maths): 45
Marks(Eng): 56
Name: Parth
Roll No.: 454
Age: 435
Marks(sci): 56
Marks(Maths): 67
Marks(Eng): 5
Name: Juhil
Roll No.: 23
Age: 54
Marks(sci): 76677
Marks(Maths): 87
Marks(Eng): 67


--------Details of students--------
Student Name is  Aryan
	Roll no.:  56
	Age:  45
	Marks in Science: 56 ; Maths: 45 ; English:  56


Student Name is  Parth
	Roll no.:  454
	Age:  435
	Marks in Science: 56 ; Maths: 67 ; English:  5


Student Name is  Juhil
	Roll no.:  23
	Age:  54
	Marks in Science: 76677 ; Maths: 87 ; English:  67


-----------------------------------


In [16]:
class bike:
    def __init__(self,company,price,model):
        self.name=company='NA'
        self.price=price='NA'
        self.model=model='NA'
        
    def details(self):
        print("Company Name: ",self.name)
        print("price: ",self.price)
        
    def mileage(self):
        if self.model=='1':
            print("mileage of "+self.name+" model 1 is 28")
            
        if self.model=='2':
            print("mileage of "+self.name+"model 2 is 35")
            
        if self.model=='3':
            print("mileage of "+self.name+"model 3 is 45")
        
        if self.model=='NA':
            print("mileage not defined")
            
            
            
            
print("Note: Models only 1,2,3 are available")
n=int(input("how many bikes: "))
b={}
com={}
prc={}
mod={}
for i in range(1,n+1):
    com[i]=input("company name: ")
    prc[i]=input("price: ")
    mod[i]=input("model no.:")
    
print("\n-------------------Details of bike-----------------\n")
    
for i in range(1,n+1):
    b[i]=bike(com[i],prc[i],mod[i])
    b[i].details()
    b[i].mileage()

Note: Models only 1,2,3 are available
how many bikes: 1
company name: 
price: 
model no.:

-------------------Details of bike-----------------

Company Name:  NA
price:  NA
mileage not defined


In [4]:
class trial:
    def __init__(self,name,last_name):
        self.n1=name
        self.n2=last_name
        
    def __str__(self):
        return 'My name is {self.n1} {self.n2}.'.format(self=self)

a=trial('Aryan','Patel')
print(a)

My name is Aryan Patel.


# Inheritance

In [18]:
class school:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        
class std1(school):
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no

    def intro(self):
        print("My name is ",self.name,". Roll Number is ",self.roll_no,". My standard is 1st standard.")
        
    
        
a=std1('Aryan','35')
a.intro()

My name is  Aryan . Roll Number is  35 . My standard is 1st standard.


# Exception Handling

In [ ]:
#(try) and (except) are the words used in exception handling

In [11]:
x=0
try:
    a=9/x
    print(a)
except Exception as e:
    print('Error')
    print(e)

Error
division by zero


In [19]:
#for to understan
try:
    print(OurVar)
except NameError:
    print("Variable not defined")
except:
    print("Other Error")

Variable not defined


# Files I/O

In [1]:
# File I/O Basics

# "r"=open file for reading
# "w"=open a file for writing
# "x"=creates file if not exists
# "a"=Add more content to a file or you can say append
# "t"=text mode
# "b"=binary mode
# "+"=read and write 

'\n"r"=open file for reading\n"w"=open a file for writing\n"x"=creates file if not exists\n"a"=Add more content to a file or you can say append\n"t"=text mode\n"b"=binary mode\n"+"=read and write \n\n'

In [36]:
f=open("aryan.txt","rt")
content=f.read()
print(content)
f.close()

f1=open("aryan.txt","rt")
content4=f1.read(4)
print(content4)
f1.close()


Aryan Patel is in surat
Hello World
Hello Moto
Bye Bye!!
Arya


In [14]:
f=open("Aryan.txt","rt")

for a in f: #it will go line by line in aryan.txt
    print(a)
    
f.close()

f=open("Aryan.txt","rt")
print(f.read())
f.close()

Aryan Patel is in surat

Hello World

Hello Moto

Bye Bye!!1234567891011121314151617181920

1234567891011121314151617181920
Aryan Patel is in surat
Hello World
Hello Moto
Bye Bye!!1234567891011121314151617181920
1234567891011121314151617181920


In [39]:
a=input()
f=open("Aryan1.txt","wt")
f.write(a)
f.close()

I am Aryan Patel from surat,Gujarat. Studying in NIT Srinagar


In [42]:
# append in files
a="\n1234567891011121314151617181920"
f=open("Aryan.txt","a+")
f.write(a)
print(f.read())
f.close()


In [1]:
#another way of writting
file_name='Aryan.txt'
with open(file_name) as f:
    a=f.read()
    print(a)

Aryan Patel is in surat
Hello World
Hello Moto
Bye Bye!!1234567891011121314151617181920
1234567891011121314151617181920


In [4]:
#readline will read only first line
f=open("Aryan.txt","r")
a=f.readline()
print(a)

Aryan Patel is in surat



# Numpy

In [ ]:
# vectors are 1d array
#matrix are 2d array

In [22]:
#creating a simple array similar to list
import numpy as np
a=np.array([1,2,3])
print(a)
print(a[0])
print(a[1])
print(a[2])

[1 2 3]
1
2
3


In [23]:
#3 benefits of numpy array over a python list
#1.) less memory
#2.) Fast
#3.) Convinient

In [27]:
#if we have to make an array of continuous number
import numpy as np
a=np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [29]:
import numpy as np
a=np.arange(0,100,2)
print(a)
#extra properties of arange

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [35]:
#2d array
import numpy as np
a=np.array([[1,2],[2,3],[3,4]])
print(a)
print("the dimension of array is ",end="") #end="" is used to print the next line in same line
print(a.ndim) # ndim print dimension of array a 
#ndim can be used in 1d array

[[1 2]
 [2 3]
 [3 4]]
the dimension of array is 2


In [42]:
#generating zeroes and ones
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
print(a)
#you put directly 'a' comma will appear if you use print then comma will not appear 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
#using linspace
#by using linspace
# reurns evenly spaced numbers over specified intervals

In [4]:
import numpy as np
a=np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [1]:
# using rand
#you can generate random array of given size

import numpy as np
np.random.rand(5)

#here 5 is the how much elements should be there in array numbers are randomly generated

array([0.903969  , 0.60786523, 0.9335007 , 0.72294165, 0.90961768])

In [5]:
# using randint
# we can generate random integer
#
import numpy as np
np.random.randint(1,100)

5

In [1]:
a=None
print(a)

None
